# --- auto generated GDIS makefile

USE_GUI = YES
USE_GRISU = NO
include makefile.osx
include makefile.src

CFLAGS := $(CFLAGS) -DWITH_GUI 
INCS := $(INCS) `pkg-config --cflags gtk+-2.0 gthread-2.0 gtkglext-1.0 gmodule-2.0` 
LIBS := $(LIBS) `pkg-config --libs gtk+-2.0 gthread-2.0 gtkglext-1.0 gmodule-2.0` 

OBJ = $(SRC:.c=.o)

gdis: $(OBJ)
	$(CC) $(OBJ) $(LDFLAGS) -o gdis $(LIBS)
.c.o:
	$(CC) $(CFLAGS) -c $< $(INCS)
clean:
	 rm -rf *.o
depend: $(SRC)
	makedepend $(INCS) -I/opt/local/lib/gcc48/gcc/x86_64-apple-darwin14/4.8.4/include $^

# DO NOT DELETE THIS LINE -- make depend needs it
