/* soapStub.h
   Generated by gSOAP 2.7.9k from grisu_ws.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE__xop__Include
#define SOAP_TYPE__xop__Include (6)
/* Base64 schema type: */
struct _xop__Include
{
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (10)
/* Base64 schema type: */
struct xsd__base64Binary
{
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (12)
/* ns1:ArrayOfString */
struct ns1__ArrayOfString
{
	int __sizestring;	/* sequence of elements <string> */
	char **string;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__anyType2anyTypeMap_entry
#define SOAP_TYPE__ns1__anyType2anyTypeMap_entry (15)
/* ns1:anyType2anyTypeMap-entry */
struct _ns1__anyType2anyTypeMap_entry
{
	char *key;	/* optional element of type xsd:anyType */
	char *value;	/* optional element of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE_ns1__anyType2anyTypeMap
#define SOAP_TYPE_ns1__anyType2anyTypeMap (14)
/* ns1:anyType2anyTypeMap */
struct ns1__anyType2anyTypeMap
{
	int __sizeentry;	/* sequence of elements <entry> */
	struct _ns1__anyType2anyTypeMap_entry *entry;	/* optional element of type ns1:anyType2anyTypeMap-entry */
};
#endif

#ifndef SOAP_TYPE__ns1__getChildrenFiles
#define SOAP_TYPE__ns1__getChildrenFiles (17)
/* ns1:getChildrenFiles */
struct _ns1__getChildrenFiles
{
	char *in0;	/* required element of type xsd:string */
	enum xsd__boolean in1;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__getChildrenFilesResponse
#define SOAP_TYPE__ns1__getChildrenFilesResponse (18)
/* ns1:getChildrenFilesResponse */
struct _ns1__getChildrenFilesResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobFqan
#define SOAP_TYPE__ns1__getJobFqan (20)
/* ns1:getJobFqan */
struct _ns1__getJobFqan
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobFqanResponse
#define SOAP_TYPE__ns1__getJobFqanResponse (21)
/* ns1:getJobFqanResponse */
struct _ns1__getJobFqanResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__mount
#define SOAP_TYPE__ns1__mount (22)
/* ns1:mount */
struct _ns1__mount
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
	enum xsd__boolean in2;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__mountResponse
#define SOAP_TYPE__ns1__mountResponse (23)
/* ns1:mountResponse */
struct _ns1__mountResponse
{
	struct ns3__MountPoint *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns3:MountPoint */
};
#endif

#ifndef SOAP_TYPE__ns1__login
#define SOAP_TYPE__ns1__login (26)
/* ns1:login */
struct _ns1__login
{
	char *in0;	/* required element of type xsd:string */
	struct ns1__ArrayOfString *in1;	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__loginResponse
#define SOAP_TYPE__ns1__loginResponse (27)
/* ns1:loginResponse */
struct _ns1__loginResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getTemplate
#define SOAP_TYPE__ns1__getTemplate (28)
/* ns1:getTemplate */
struct _ns1__getTemplate
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getTemplateResponse
#define SOAP_TYPE__ns1__getTemplateResponse (29)
/* ns1:getTemplateResponse */
struct _ns1__getTemplateResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE__ns1__getFqans
#define SOAP_TYPE__ns1__getFqans (30)
/* ns1:getFqans */
struct _ns1__getFqans
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getFqansResponse
#define SOAP_TYPE__ns1__getFqansResponse (31)
/* ns1:getFqansResponse */
struct _ns1__getFqansResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__df
#define SOAP_TYPE__ns1__df (32)
/* ns1:df */
struct _ns1__df
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__dfResponse
#define SOAP_TYPE__ns1__dfResponse (33)
/* ns1:dfResponse */
struct _ns1__dfResponse
{
	struct ns3__ArrayOfMountPoint *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns3:ArrayOfMountPoint */
};
#endif

#ifndef SOAP_TYPE__ns1__downloadByteArray
#define SOAP_TYPE__ns1__downloadByteArray (36)
/* ns1:downloadByteArray */
struct _ns1__downloadByteArray
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__downloadByteArrayResponse
#define SOAP_TYPE__ns1__downloadByteArrayResponse (37)
/* ns1:downloadByteArrayResponse */
struct _ns1__downloadByteArrayResponse
{
	struct xsd__base64Binary *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:base64Binary */
};
#endif

#ifndef SOAP_TYPE__ns1__getSubmissionLocationsForApplication2
#define SOAP_TYPE__ns1__getSubmissionLocationsForApplication2 (39)
/* ns1:getSubmissionLocationsForApplication2 */
struct _ns1__getSubmissionLocationsForApplication2
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
	char *in2;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getSubmissionLocationsForApplication2Response
#define SOAP_TYPE__ns1__getSubmissionLocationsForApplication2Response (40)
/* ns1:getSubmissionLocationsForApplication2Response */
struct _ns1__getSubmissionLocationsForApplication2Response
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__ps
#define SOAP_TYPE__ns1__ps (41)
/* ns1:ps */
struct _ns1__ps
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__psResponse
#define SOAP_TYPE__ns1__psResponse (42)
/* ns1:psResponse */
struct _ns1__psResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE__ns1__getStagingFileSystemForSubmissionLocation
#define SOAP_TYPE__ns1__getStagingFileSystemForSubmissionLocation (43)
/* ns1:getStagingFileSystemForSubmissionLocation */
struct _ns1__getStagingFileSystemForSubmissionLocation
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getStagingFileSystemForSubmissionLocationResponse
#define SOAP_TYPE__ns1__getStagingFileSystemForSubmissionLocationResponse (44)
/* ns1:getStagingFileSystemForSubmissionLocationResponse */
struct _ns1__getStagingFileSystemForSubmissionLocationResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__getUserProperty
#define SOAP_TYPE__ns1__getUserProperty (45)
/* ns1:getUserProperty */
struct _ns1__getUserProperty
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getUserPropertyResponse
#define SOAP_TYPE__ns1__getUserPropertyResponse (46)
/* ns1:getUserPropertyResponse */
struct _ns1__getUserPropertyResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__mkdir
#define SOAP_TYPE__ns1__mkdir (47)
/* ns1:mkdir */
struct _ns1__mkdir
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__mkdirResponse
#define SOAP_TYPE__ns1__mkdirResponse (48)
/* ns1:mkdirResponse */
struct _ns1__mkdirResponse
{
	enum xsd__boolean out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__getDataLocationsForVO
#define SOAP_TYPE__ns1__getDataLocationsForVO (49)
/* ns1:getDataLocationsForVO */
struct _ns1__getDataLocationsForVO
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getDataLocationsForVOResponse
#define SOAP_TYPE__ns1__getDataLocationsForVOResponse (50)
/* ns1:getDataLocationsForVOResponse */
struct _ns1__getDataLocationsForVOResponse
{
	struct ns1__anyType2anyTypeMap *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:anyType2anyTypeMap */
};
#endif

#ifndef SOAP_TYPE__ns1__getSubmissionLocationsPerVersionOfApplication
#define SOAP_TYPE__ns1__getSubmissionLocationsPerVersionOfApplication (52)
/* ns1:getSubmissionLocationsPerVersionOfApplication */
struct _ns1__getSubmissionLocationsPerVersionOfApplication
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getSubmissionLocationsPerVersionOfApplicationResponse
#define SOAP_TYPE__ns1__getSubmissionLocationsPerVersionOfApplicationResponse (53)
/* ns1:getSubmissionLocationsPerVersionOfApplicationResponse */
struct _ns1__getSubmissionLocationsPerVersionOfApplicationResponse
{
	struct ns1__anyType2anyTypeMap *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:anyType2anyTypeMap */
};
#endif

#ifndef SOAP_TYPE__ns1__getTemplate1
#define SOAP_TYPE__ns1__getTemplate1 (54)
/* ns1:getTemplate1 */
struct _ns1__getTemplate1
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getTemplate1Response
#define SOAP_TYPE__ns1__getTemplate1Response (55)
/* ns1:getTemplate1Response */
struct _ns1__getTemplate1Response
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE__ns1__downloadByteArray1
#define SOAP_TYPE__ns1__downloadByteArray1 (56)
/* ns1:downloadByteArray1 */
struct _ns1__downloadByteArray1
{
	char *in0;	/* required element of type xsd:string */
	int in1;	/* required element of type xsd:int */
	int in2;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__downloadByteArray1Response
#define SOAP_TYPE__ns1__downloadByteArray1Response (57)
/* ns1:downloadByteArray1Response */
struct _ns1__downloadByteArray1Response
{
	struct xsd__base64Binary *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:base64Binary */
};
#endif

#ifndef SOAP_TYPE__ns1__listHostedApplicationTemplates
#define SOAP_TYPE__ns1__listHostedApplicationTemplates (58)
/* ns1:listHostedApplicationTemplates */
struct _ns1__listHostedApplicationTemplates
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__listHostedApplicationTemplatesResponse
#define SOAP_TYPE__ns1__listHostedApplicationTemplatesResponse (59)
/* ns1:listHostedApplicationTemplatesResponse */
struct _ns1__listHostedApplicationTemplatesResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__deleteFiles
#define SOAP_TYPE__ns1__deleteFiles (60)
/* ns1:deleteFiles */
struct _ns1__deleteFiles
{
	struct ns1__ArrayOfString *in0;	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__deleteFilesResponse
#define SOAP_TYPE__ns1__deleteFilesResponse (61)
/* ns1:deleteFilesResponse */
struct _ns1__deleteFilesResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getMessagesSince
#define SOAP_TYPE__ns1__getMessagesSince (62)
/* ns1:getMessagesSince */
struct _ns1__getMessagesSince
{
	time_t in0;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__ns1__getMessagesSinceResponse
#define SOAP_TYPE__ns1__getMessagesSinceResponse (64)
/* ns1:getMessagesSinceResponse */
struct _ns1__getMessagesSinceResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE__ns1__calculateAbsoluteJobDirectory
#define SOAP_TYPE__ns1__calculateAbsoluteJobDirectory (65)
/* ns1:calculateAbsoluteJobDirectory */
struct _ns1__calculateAbsoluteJobDirectory
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
	char *in2;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__calculateAbsoluteJobDirectoryResponse
#define SOAP_TYPE__ns1__calculateAbsoluteJobDirectoryResponse (66)
/* ns1:calculateAbsoluteJobDirectoryResponse */
struct _ns1__calculateAbsoluteJobDirectoryResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__ls_USCOREstring
#define SOAP_TYPE__ns1__ls_USCOREstring (67)
/* ns1:ls_string */
struct _ns1__ls_USCOREstring
{
	char *in0;	/* required element of type xsd:string */
	int in1;	/* required element of type xsd:int */
	enum xsd__boolean in2;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__ls_USCOREstringResponse
#define SOAP_TYPE__ns1__ls_USCOREstringResponse (68)
/* ns1:ls_stringResponse */
struct _ns1__ls_USCOREstringResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getSubmissionLocationsForApplication1
#define SOAP_TYPE__ns1__getSubmissionLocationsForApplication1 (69)
/* ns1:getSubmissionLocationsForApplication1 */
struct _ns1__getSubmissionLocationsForApplication1
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getSubmissionLocationsForApplication1Response
#define SOAP_TYPE__ns1__getSubmissionLocationsForApplication1Response (70)
/* ns1:getSubmissionLocationsForApplication1Response */
struct _ns1__getSubmissionLocationsForApplication1Response
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__getApplicationDetails
#define SOAP_TYPE__ns1__getApplicationDetails (71)
/* ns1:getApplicationDetails */
struct _ns1__getApplicationDetails
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getApplicationDetailsResponse
#define SOAP_TYPE__ns1__getApplicationDetailsResponse (72)
/* ns1:getApplicationDetailsResponse */
struct _ns1__getApplicationDetailsResponse
{
	struct ns1__anyType2anyTypeMap *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:anyType2anyTypeMap */
};
#endif

#ifndef SOAP_TYPE__ns1__createJob1
#define SOAP_TYPE__ns1__createJob1 (73)
/* ns1:createJob1 */
struct _ns1__createJob1
{
	char *in0;	/* required element of type xsd:anyType */
	int in1;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__createJob1Response
#define SOAP_TYPE__ns1__createJob1Response (74)
/* ns1:createJob1Response */
struct _ns1__createJob1Response
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getSubmissionLocationsForApplication
#define SOAP_TYPE__ns1__getSubmissionLocationsForApplication (75)
/* ns1:getSubmissionLocationsForApplication */
struct _ns1__getSubmissionLocationsForApplication
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getSubmissionLocationsForApplicationResponse
#define SOAP_TYPE__ns1__getSubmissionLocationsForApplicationResponse (76)
/* ns1:getSubmissionLocationsForApplicationResponse */
struct _ns1__getSubmissionLocationsForApplicationResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__getDN
#define SOAP_TYPE__ns1__getDN (77)
/* ns1:getDN */
struct _ns1__getDN
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getDNResponse
#define SOAP_TYPE__ns1__getDNResponse (78)
/* ns1:getDNResponse */
struct _ns1__getDNResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllJobnames
#define SOAP_TYPE__ns1__getAllJobnames (79)
/* ns1:getAllJobnames */
struct _ns1__getAllJobnames
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getAllJobnamesResponse
#define SOAP_TYPE__ns1__getAllJobnamesResponse (80)
/* ns1:getAllJobnamesResponse */
struct _ns1__getAllJobnamesResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllJobProperties
#define SOAP_TYPE__ns1__getAllJobProperties (81)
/* ns1:getAllJobProperties */
struct _ns1__getAllJobProperties
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllJobPropertiesResponse
#define SOAP_TYPE__ns1__getAllJobPropertiesResponse (82)
/* ns1:getAllJobPropertiesResponse */
struct _ns1__getAllJobPropertiesResponse
{
	struct ns1__anyType2anyTypeMap *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:anyType2anyTypeMap */
};
#endif

#ifndef SOAP_TYPE__ns1__download
#define SOAP_TYPE__ns1__download (83)
/* ns1:download */
struct _ns1__download
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__downloadResponse
#define SOAP_TYPE__ns1__downloadResponse (84)
/* ns1:downloadResponse */
struct _ns1__downloadResponse
{
	struct xsd__base64Binary *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:base64Binary */
};
#endif

#ifndef SOAP_TYPE__ns1__isFolder
#define SOAP_TYPE__ns1__isFolder (85)
/* ns1:isFolder */
struct _ns1__isFolder
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__isFolderResponse
#define SOAP_TYPE__ns1__isFolderResponse (86)
/* ns1:isFolderResponse */
struct _ns1__isFolderResponse
{
	enum xsd__boolean out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__kill
#define SOAP_TYPE__ns1__kill (87)
/* ns1:kill */
struct _ns1__kill
{
	char *in0;	/* required element of type xsd:string */
	enum xsd__boolean in1;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__killResponse
#define SOAP_TYPE__ns1__killResponse (88)
/* ns1:killResponse */
struct _ns1__killResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getAllAvailableApplications
#define SOAP_TYPE__ns1__getAllAvailableApplications (89)
/* ns1:getAllAvailableApplications */
struct _ns1__getAllAvailableApplications
{
	struct ns1__ArrayOfString *in0;	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllAvailableApplicationsResponse
#define SOAP_TYPE__ns1__getAllAvailableApplicationsResponse (90)
/* ns1:getAllAvailableApplicationsResponse */
struct _ns1__getAllAvailableApplicationsResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__addJobProperties
#define SOAP_TYPE__ns1__addJobProperties (91)
/* ns1:addJobProperties */
struct _ns1__addJobProperties
{
	char *in0;	/* required element of type xsd:string */
	struct ns1__anyType2anyTypeMap *in1;	/* required element of type ns1:anyType2anyTypeMap */
};
#endif

#ifndef SOAP_TYPE__ns1__addJobPropertiesResponse
#define SOAP_TYPE__ns1__addJobPropertiesResponse (92)
/* ns1:addJobPropertiesResponse */
struct _ns1__addJobPropertiesResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__addJobProperty
#define SOAP_TYPE__ns1__addJobProperty (93)
/* ns1:addJobProperty */
struct _ns1__addJobProperty
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
	char *in2;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__addJobPropertyResponse
#define SOAP_TYPE__ns1__addJobPropertyResponse (94)
/* ns1:addJobPropertyResponse */
struct _ns1__addJobPropertyResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getAllSubmissionLocations
#define SOAP_TYPE__ns1__getAllSubmissionLocations (95)
/* ns1:getAllSubmissionLocations */
struct _ns1__getAllSubmissionLocations
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getAllSubmissionLocationsResponse
#define SOAP_TYPE__ns1__getAllSubmissionLocationsResponse (96)
/* ns1:getAllSubmissionLocationsResponse */
struct _ns1__getAllSubmissionLocationsResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__getInterfaceVersion
#define SOAP_TYPE__ns1__getInterfaceVersion (97)
/* ns1:getInterfaceVersion */
struct _ns1__getInterfaceVersion
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getInterfaceVersionResponse
#define SOAP_TYPE__ns1__getInterfaceVersionResponse (98)
/* ns1:getInterfaceVersionResponse */
struct _ns1__getInterfaceVersionResponse
{
	double out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE__ns1__createJob
#define SOAP_TYPE__ns1__createJob (100)
/* ns1:createJob */
struct _ns1__createJob
{
	char *in0;	/* required element of type xsd:string */
	int in1;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__createJobResponse
#define SOAP_TYPE__ns1__createJobResponse (101)
/* ns1:createJobResponse */
struct _ns1__createJobResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllSubmissionLocations1
#define SOAP_TYPE__ns1__getAllSubmissionLocations1 (102)
/* ns1:getAllSubmissionLocations1 */
struct _ns1__getAllSubmissionLocations1
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getAllSubmissionLocations1Response
#define SOAP_TYPE__ns1__getAllSubmissionLocations1Response (103)
/* ns1:getAllSubmissionLocations1Response */
struct _ns1__getAllSubmissionLocations1Response
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__getVersionsOfApplicationOnSite
#define SOAP_TYPE__ns1__getVersionsOfApplicationOnSite (104)
/* ns1:getVersionsOfApplicationOnSite */
struct _ns1__getVersionsOfApplicationOnSite
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getVersionsOfApplicationOnSiteResponse
#define SOAP_TYPE__ns1__getVersionsOfApplicationOnSiteResponse (105)
/* ns1:getVersionsOfApplicationOnSiteResponse */
struct _ns1__getVersionsOfApplicationOnSiteResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__uploadByteArray1
#define SOAP_TYPE__ns1__uploadByteArray1 (106)
/* ns1:uploadByteArray1 */
struct _ns1__uploadByteArray1
{
	struct xsd__base64Binary *in0;	/* required element of type xsd:base64Binary */
	char *in1;	/* required element of type xsd:string */
	enum xsd__boolean in2;	/* required element of type xsd:boolean */
	int in3;	/* required element of type xsd:int */
	int in4;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__uploadByteArray1Response
#define SOAP_TYPE__ns1__uploadByteArray1Response (107)
/* ns1:uploadByteArray1Response */
struct _ns1__uploadByteArray1Response
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__ps_USCOREstring
#define SOAP_TYPE__ns1__ps_USCOREstring (108)
/* ns1:ps_string */
struct _ns1__ps_USCOREstring
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__ps_USCOREstringResponse
#define SOAP_TYPE__ns1__ps_USCOREstringResponse (109)
/* ns1:ps_stringResponse */
struct _ns1__ps_USCOREstringResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getSite
#define SOAP_TYPE__ns1__getSite (110)
/* ns1:getSite */
struct _ns1__getSite
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getSiteResponse
#define SOAP_TYPE__ns1__getSiteResponse (111)
/* ns1:getSiteResponse */
struct _ns1__getSiteResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__lastModified
#define SOAP_TYPE__ns1__lastModified (112)
/* ns1:lastModified */
struct _ns1__lastModified
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__lastModifiedResponse
#define SOAP_TYPE__ns1__lastModifiedResponse (113)
/* ns1:lastModifiedResponse */
struct _ns1__lastModifiedResponse
{
	LONG64 out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE__ns1__ls
#define SOAP_TYPE__ns1__ls (115)
/* ns1:ls */
struct _ns1__ls
{
	char *in0;	/* required element of type xsd:string */
	int in1;	/* required element of type xsd:int */
	enum xsd__boolean in2;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__lsResponse
#define SOAP_TYPE__ns1__lsResponse (116)
/* ns1:lsResponse */
struct _ns1__lsResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE__ns1__getApplicationDetails1
#define SOAP_TYPE__ns1__getApplicationDetails1 (117)
/* ns1:getApplicationDetails1 */
struct _ns1__getApplicationDetails1
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
	char *in2;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getApplicationDetails1Response
#define SOAP_TYPE__ns1__getApplicationDetails1Response (118)
/* ns1:getApplicationDetails1Response */
struct _ns1__getApplicationDetails1Response
{
	struct ns1__anyType2anyTypeMap *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:anyType2anyTypeMap */
};
#endif

#ifndef SOAP_TYPE__ns1__calculateRelativeJobDirectory
#define SOAP_TYPE__ns1__calculateRelativeJobDirectory (119)
/* ns1:calculateRelativeJobDirectory */
struct _ns1__calculateRelativeJobDirectory
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__calculateRelativeJobDirectoryResponse
#define SOAP_TYPE__ns1__calculateRelativeJobDirectoryResponse (120)
/* ns1:calculateRelativeJobDirectoryResponse */
struct _ns1__calculateRelativeJobDirectoryResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__setJobDescription_USCOREstring
#define SOAP_TYPE__ns1__setJobDescription_USCOREstring (121)
/* ns1:setJobDescription_string */
struct _ns1__setJobDescription_USCOREstring
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__setJobDescription_USCOREstringResponse
#define SOAP_TYPE__ns1__setJobDescription_USCOREstringResponse (122)
/* ns1:setJobDescription_stringResponse */
struct _ns1__setJobDescription_USCOREstringResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__logout
#define SOAP_TYPE__ns1__logout (123)
/* ns1:logout */
struct _ns1__logout
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__logoutResponse
#define SOAP_TYPE__ns1__logoutResponse (124)
/* ns1:logoutResponse */
struct _ns1__logoutResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__submitJob
#define SOAP_TYPE__ns1__submitJob (125)
/* ns1:submitJob */
struct _ns1__submitJob
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__submitJobResponse
#define SOAP_TYPE__ns1__submitJobResponse (126)
/* ns1:submitJobResponse */
struct _ns1__submitJobResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__uploadByteArray
#define SOAP_TYPE__ns1__uploadByteArray (127)
/* ns1:uploadByteArray */
struct _ns1__uploadByteArray
{
	struct xsd__base64Binary *in0;	/* required element of type xsd:base64Binary */
	char *in1;	/* required element of type xsd:string */
	enum xsd__boolean in2;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__uploadByteArrayResponse
#define SOAP_TYPE__ns1__uploadByteArrayResponse (128)
/* ns1:uploadByteArrayResponse */
struct _ns1__uploadByteArrayResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__cp
#define SOAP_TYPE__ns1__cp (129)
/* ns1:cp */
struct _ns1__cp
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
	enum xsd__boolean in2;	/* required element of type xsd:boolean */
	enum xsd__boolean in3;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__cpResponse
#define SOAP_TYPE__ns1__cpResponse (130)
/* ns1:cpResponse */
struct _ns1__cpResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getFileSize
#define SOAP_TYPE__ns1__getFileSize (131)
/* ns1:getFileSize */
struct _ns1__getFileSize
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getFileSizeResponse
#define SOAP_TYPE__ns1__getFileSizeResponse (132)
/* ns1:getFileSizeResponse */
struct _ns1__getFileSizeResponse
{
	LONG64 out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE__ns1__deleteFile
#define SOAP_TYPE__ns1__deleteFile (133)
/* ns1:deleteFile */
struct _ns1__deleteFile
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__deleteFileResponse
#define SOAP_TYPE__ns1__deleteFileResponse (134)
/* ns1:deleteFileResponse */
struct _ns1__deleteFileResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__upload
#define SOAP_TYPE__ns1__upload (135)
/* ns1:upload */
struct _ns1__upload
{
	struct xsd__base64Binary *in0;	/* required element of type xsd:base64Binary */
	char *in1;	/* required element of type xsd:string */
	enum xsd__boolean in2;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__uploadResponse
#define SOAP_TYPE__ns1__uploadResponse (136)
/* ns1:uploadResponse */
struct _ns1__uploadResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobDirectory
#define SOAP_TYPE__ns1__getJobDirectory (137)
/* ns1:getJobDirectory */
struct _ns1__getJobDirectory
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobDirectoryResponse
#define SOAP_TYPE__ns1__getJobDirectoryResponse (138)
/* ns1:getJobDirectoryResponse */
struct _ns1__getJobDirectoryResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__setJobDescription
#define SOAP_TYPE__ns1__setJobDescription (139)
/* ns1:setJobDescription */
struct _ns1__setJobDescription
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE__ns1__setJobDescriptionResponse
#define SOAP_TYPE__ns1__setJobDescriptionResponse (140)
/* ns1:setJobDescriptionResponse */
struct _ns1__setJobDescriptionResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getAllSites
#define SOAP_TYPE__ns1__getAllSites (141)
/* ns1:getAllSites */
struct _ns1__getAllSites
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getAllSitesResponse
#define SOAP_TYPE__ns1__getAllSitesResponse (142)
/* ns1:getAllSitesResponse */
struct _ns1__getAllSitesResponse
{
	struct ns1__ArrayOfString *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobDetails_USCOREstring
#define SOAP_TYPE__ns1__getJobDetails_USCOREstring (143)
/* ns1:getJobDetails_string */
struct _ns1__getJobDetails_USCOREstring
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobDetails_USCOREstringResponse
#define SOAP_TYPE__ns1__getJobDetails_USCOREstringResponse (144)
/* ns1:getJobDetails_stringResponse */
struct _ns1__getJobDetails_USCOREstringResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobStatus
#define SOAP_TYPE__ns1__getJobStatus (145)
/* ns1:getJobStatus */
struct _ns1__getJobStatus
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobStatusResponse
#define SOAP_TYPE__ns1__getJobStatusResponse (146)
/* ns1:getJobStatusResponse */
struct _ns1__getJobStatusResponse
{
	int out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__umount
#define SOAP_TYPE__ns1__umount (147)
/* ns1:umount */
struct _ns1__umount
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__umountResponse
#define SOAP_TYPE__ns1__umountResponse (148)
/* ns1:umountResponse */
struct _ns1__umountResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getJobDetails
#define SOAP_TYPE__ns1__getJobDetails (149)
/* ns1:getJobDetails */
struct _ns1__getJobDetails
{
	char *in0;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobDetailsResponse
#define SOAP_TYPE__ns1__getJobDetailsResponse (150)
/* ns1:getJobDetailsResponse */
struct _ns1__getJobDetailsResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE__ns1__mount1
#define SOAP_TYPE__ns1__mount1 (151)
/* ns1:mount1 */
struct _ns1__mount1
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
	char *in2;	/* required element of type xsd:string */
	enum xsd__boolean in3;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__mount1Response
#define SOAP_TYPE__ns1__mount1Response (152)
/* ns1:mount1Response */
struct _ns1__mount1Response
{
	struct ns3__MountPoint *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns3:MountPoint */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobProperty
#define SOAP_TYPE__ns1__getJobProperty (153)
/* ns1:getJobProperty */
struct _ns1__getJobProperty
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__getJobPropertyResponse
#define SOAP_TYPE__ns1__getJobPropertyResponse (154)
/* ns1:getJobPropertyResponse */
struct _ns1__getJobPropertyResponse
{
	char *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__submitSupportRequest
#define SOAP_TYPE__ns1__submitSupportRequest (155)
/* ns1:submitSupportRequest */
struct _ns1__submitSupportRequest
{
	char *in0;	/* required element of type xsd:string */
	char *in1;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__submitSupportRequestResponse
#define SOAP_TYPE__ns1__submitSupportRequestResponse (156)
/* ns1:submitSupportRequestResponse */
struct _ns1__submitSupportRequestResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getAllHosts
#define SOAP_TYPE__ns1__getAllHosts (157)
/* ns1:getAllHosts */
struct _ns1__getAllHosts
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__getAllHostsResponse
#define SOAP_TYPE__ns1__getAllHostsResponse (158)
/* ns1:getAllHostsResponse */
struct _ns1__getAllHostsResponse
{
	struct ns1__anyType2anyTypeMap *out;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:anyType2anyTypeMap */
};
#endif

#ifndef SOAP_TYPE_ns2__VomsException
#define SOAP_TYPE_ns2__VomsException (159)
/* ns2:VomsException */
struct ns2__VomsException
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns2__RemoteFileSystemException
#define SOAP_TYPE_ns2__RemoteFileSystemException (160)
/* ns2:RemoteFileSystemException */
struct ns2__RemoteFileSystemException
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns2__NoSuchJobException
#define SOAP_TYPE_ns2__NoSuchJobException (161)
/* ns2:NoSuchJobException */
struct ns2__NoSuchJobException
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns2__NoValidCredentialException
#define SOAP_TYPE_ns2__NoValidCredentialException (162)
/* ns2:NoValidCredentialException */
struct ns2__NoValidCredentialException
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns2__NoSuchTemplateException
#define SOAP_TYPE_ns2__NoSuchTemplateException (163)
/* ns2:NoSuchTemplateException */
struct ns2__NoSuchTemplateException
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns2__JobDescriptionNotValidException
#define SOAP_TYPE_ns2__JobDescriptionNotValidException (164)
/* ns2:JobDescriptionNotValidException */
struct ns2__JobDescriptionNotValidException
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns2__JobSubmissionException
#define SOAP_TYPE_ns2__JobSubmissionException (165)
/* ns2:JobSubmissionException */
struct ns2__JobSubmissionException
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns3__MountPoint
#define SOAP_TYPE_ns3__MountPoint (24)
/* ns3:MountPoint */
struct ns3__MountPoint
{
	enum xsd__boolean *automaticallyMounted;	/* optional element of type xsd:boolean */
	enum xsd__boolean *disabled;	/* optional element of type xsd:boolean */
	char *dn;	/* optional element of type xsd:string */
	char *fqan;	/* optional element of type xsd:string */
	LONG64 *mountPointId;	/* optional element of type xsd:long */
	char *mountpoint;	/* optional element of type xsd:string */
	char *rootUrl;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__ArrayOfMountPoint
#define SOAP_TYPE_ns3__ArrayOfMountPoint (34)
/* ns3:ArrayOfMountPoint */
struct ns3__ArrayOfMountPoint
{
	int __sizeMountPoint;	/* sequence of elements <MountPoint> */
	struct ns3__MountPoint *MountPoint;	/* optional element of type ns3:MountPoint */
};
#endif

#ifndef SOAP_TYPE_ns4__JobCreationException
#define SOAP_TYPE_ns4__JobCreationException (168)
/* ns4:JobCreationException */
struct ns4__JobCreationException
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (169)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	struct ns4__JobCreationException *ns1__JobCreationException;	/* optional element of type ns4:JobCreationException */
	struct ns2__JobDescriptionNotValidException *ns1__JobDescriptionNotValidException;	/* optional element of type ns2:JobDescriptionNotValidException */
	struct ns2__JobSubmissionException *ns1__JobSubmissionException;	/* optional element of type ns2:JobSubmissionException */
	struct ns2__NoSuchJobException *ns1__NoSuchJobException;	/* optional element of type ns2:NoSuchJobException */
	struct ns2__NoSuchTemplateException *ns1__NoSuchTemplateException;	/* optional element of type ns2:NoSuchTemplateException */
	struct ns2__NoValidCredentialException *ns1__NoValidCredentialException;	/* optional element of type ns2:NoValidCredentialException */
	struct ns2__RemoteFileSystemException *ns1__RemoteFileSystemException;	/* optional element of type ns2:RemoteFileSystemException */
	struct ns2__VomsException *ns1__VomsException;	/* optional element of type ns2:VomsException */
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE___ns1__getChildrenFiles
#define SOAP_TYPE___ns1__getChildrenFiles (183)
/* Operation wrapper: */
struct __ns1__getChildrenFiles
{
	struct _ns1__getChildrenFiles *ns1__getChildrenFiles;	/* optional element of type ns1:getChildrenFiles */
};
#endif

#ifndef SOAP_TYPE___ns1__getJobFqan
#define SOAP_TYPE___ns1__getJobFqan (187)
/* Operation wrapper: */
struct __ns1__getJobFqan
{
	struct _ns1__getJobFqan *ns1__getJobFqan;	/* optional element of type ns1:getJobFqan */
};
#endif

#ifndef SOAP_TYPE___ns1__mount
#define SOAP_TYPE___ns1__mount (191)
/* Operation wrapper: */
struct __ns1__mount
{
	struct _ns1__mount *ns1__mount;	/* optional element of type ns1:mount */
};
#endif

#ifndef SOAP_TYPE___ns1__login
#define SOAP_TYPE___ns1__login (195)
/* Operation wrapper: */
struct __ns1__login
{
	struct _ns1__login *ns1__login;	/* optional element of type ns1:login */
};
#endif

#ifndef SOAP_TYPE___ns1__getTemplate
#define SOAP_TYPE___ns1__getTemplate (199)
/* Operation wrapper: */
struct __ns1__getTemplate
{
	struct _ns1__getTemplate *ns1__getTemplate;	/* optional element of type ns1:getTemplate */
};
#endif

#ifndef SOAP_TYPE___ns1__getFqans
#define SOAP_TYPE___ns1__getFqans (203)
/* Operation wrapper: */
struct __ns1__getFqans
{
	struct _ns1__getFqans *ns1__getFqans;	/* optional element of type ns1:getFqans */
};
#endif

#ifndef SOAP_TYPE___ns1__df
#define SOAP_TYPE___ns1__df (207)
/* Operation wrapper: */
struct __ns1__df
{
	struct _ns1__df *ns1__df;	/* optional element of type ns1:df */
};
#endif

#ifndef SOAP_TYPE___ns1__downloadByteArray
#define SOAP_TYPE___ns1__downloadByteArray (211)
/* Operation wrapper: */
struct __ns1__downloadByteArray
{
	struct _ns1__downloadByteArray *ns1__downloadByteArray;	/* optional element of type ns1:downloadByteArray */
};
#endif

#ifndef SOAP_TYPE___ns1__getSubmissionLocationsForApplication2
#define SOAP_TYPE___ns1__getSubmissionLocationsForApplication2 (215)
/* Operation wrapper: */
struct __ns1__getSubmissionLocationsForApplication2
{
	struct _ns1__getSubmissionLocationsForApplication2 *ns1__getSubmissionLocationsForApplication2;	/* optional element of type ns1:getSubmissionLocationsForApplication2 */
};
#endif

#ifndef SOAP_TYPE___ns1__ps
#define SOAP_TYPE___ns1__ps (219)
/* Operation wrapper: */
struct __ns1__ps
{
	struct _ns1__ps *ns1__ps;	/* optional element of type ns1:ps */
};
#endif

#ifndef SOAP_TYPE___ns1__getStagingFileSystemForSubmissionLocation
#define SOAP_TYPE___ns1__getStagingFileSystemForSubmissionLocation (223)
/* Operation wrapper: */
struct __ns1__getStagingFileSystemForSubmissionLocation
{
	struct _ns1__getStagingFileSystemForSubmissionLocation *ns1__getStagingFileSystemForSubmissionLocation;	/* optional element of type ns1:getStagingFileSystemForSubmissionLocation */
};
#endif

#ifndef SOAP_TYPE___ns1__getUserProperty
#define SOAP_TYPE___ns1__getUserProperty (227)
/* Operation wrapper: */
struct __ns1__getUserProperty
{
	struct _ns1__getUserProperty *ns1__getUserProperty;	/* optional element of type ns1:getUserProperty */
};
#endif

#ifndef SOAP_TYPE___ns1__mkdir
#define SOAP_TYPE___ns1__mkdir (231)
/* Operation wrapper: */
struct __ns1__mkdir
{
	struct _ns1__mkdir *ns1__mkdir;	/* optional element of type ns1:mkdir */
};
#endif

#ifndef SOAP_TYPE___ns1__getDataLocationsForVO
#define SOAP_TYPE___ns1__getDataLocationsForVO (235)
/* Operation wrapper: */
struct __ns1__getDataLocationsForVO
{
	struct _ns1__getDataLocationsForVO *ns1__getDataLocationsForVO;	/* optional element of type ns1:getDataLocationsForVO */
};
#endif

#ifndef SOAP_TYPE___ns1__getSubmissionLocationsPerVersionOfApplication
#define SOAP_TYPE___ns1__getSubmissionLocationsPerVersionOfApplication (239)
/* Operation wrapper: */
struct __ns1__getSubmissionLocationsPerVersionOfApplication
{
	struct _ns1__getSubmissionLocationsPerVersionOfApplication *ns1__getSubmissionLocationsPerVersionOfApplication;	/* optional element of type ns1:getSubmissionLocationsPerVersionOfApplication */
};
#endif

#ifndef SOAP_TYPE___ns1__getTemplate1
#define SOAP_TYPE___ns1__getTemplate1 (243)
/* Operation wrapper: */
struct __ns1__getTemplate1
{
	struct _ns1__getTemplate1 *ns1__getTemplate1;	/* optional element of type ns1:getTemplate1 */
};
#endif

#ifndef SOAP_TYPE___ns1__downloadByteArray1
#define SOAP_TYPE___ns1__downloadByteArray1 (247)
/* Operation wrapper: */
struct __ns1__downloadByteArray1
{
	struct _ns1__downloadByteArray1 *ns1__downloadByteArray1;	/* optional element of type ns1:downloadByteArray1 */
};
#endif

#ifndef SOAP_TYPE___ns1__listHostedApplicationTemplates
#define SOAP_TYPE___ns1__listHostedApplicationTemplates (251)
/* Operation wrapper: */
struct __ns1__listHostedApplicationTemplates
{
	struct _ns1__listHostedApplicationTemplates *ns1__listHostedApplicationTemplates;	/* optional element of type ns1:listHostedApplicationTemplates */
};
#endif

#ifndef SOAP_TYPE___ns1__deleteFiles
#define SOAP_TYPE___ns1__deleteFiles (255)
/* Operation wrapper: */
struct __ns1__deleteFiles
{
	struct _ns1__deleteFiles *ns1__deleteFiles;	/* optional element of type ns1:deleteFiles */
};
#endif

#ifndef SOAP_TYPE___ns1__getMessagesSince
#define SOAP_TYPE___ns1__getMessagesSince (259)
/* Operation wrapper: */
struct __ns1__getMessagesSince
{
	struct _ns1__getMessagesSince *ns1__getMessagesSince;	/* optional element of type ns1:getMessagesSince */
};
#endif

#ifndef SOAP_TYPE___ns1__calculateAbsoluteJobDirectory
#define SOAP_TYPE___ns1__calculateAbsoluteJobDirectory (263)
/* Operation wrapper: */
struct __ns1__calculateAbsoluteJobDirectory
{
	struct _ns1__calculateAbsoluteJobDirectory *ns1__calculateAbsoluteJobDirectory;	/* optional element of type ns1:calculateAbsoluteJobDirectory */
};
#endif

#ifndef SOAP_TYPE___ns1__ls_USCOREstring
#define SOAP_TYPE___ns1__ls_USCOREstring (267)
/* Operation wrapper: */
struct __ns1__ls_USCOREstring
{
	struct _ns1__ls_USCOREstring *ns1__ls_USCOREstring;	/* optional element of type ns1:ls_string */
};
#endif

#ifndef SOAP_TYPE___ns1__getSubmissionLocationsForApplication1
#define SOAP_TYPE___ns1__getSubmissionLocationsForApplication1 (271)
/* Operation wrapper: */
struct __ns1__getSubmissionLocationsForApplication1
{
	struct _ns1__getSubmissionLocationsForApplication1 *ns1__getSubmissionLocationsForApplication1;	/* optional element of type ns1:getSubmissionLocationsForApplication1 */
};
#endif

#ifndef SOAP_TYPE___ns1__getApplicationDetails
#define SOAP_TYPE___ns1__getApplicationDetails (275)
/* Operation wrapper: */
struct __ns1__getApplicationDetails
{
	struct _ns1__getApplicationDetails *ns1__getApplicationDetails;	/* optional element of type ns1:getApplicationDetails */
};
#endif

#ifndef SOAP_TYPE___ns1__createJob1
#define SOAP_TYPE___ns1__createJob1 (279)
/* Operation wrapper: */
struct __ns1__createJob1
{
	struct _ns1__createJob1 *ns1__createJob1;	/* optional element of type ns1:createJob1 */
};
#endif

#ifndef SOAP_TYPE___ns1__getSubmissionLocationsForApplication
#define SOAP_TYPE___ns1__getSubmissionLocationsForApplication (283)
/* Operation wrapper: */
struct __ns1__getSubmissionLocationsForApplication
{
	struct _ns1__getSubmissionLocationsForApplication *ns1__getSubmissionLocationsForApplication;	/* optional element of type ns1:getSubmissionLocationsForApplication */
};
#endif

#ifndef SOAP_TYPE___ns1__getDN
#define SOAP_TYPE___ns1__getDN (287)
/* Operation wrapper: */
struct __ns1__getDN
{
	struct _ns1__getDN *ns1__getDN;	/* optional element of type ns1:getDN */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllJobnames
#define SOAP_TYPE___ns1__getAllJobnames (291)
/* Operation wrapper: */
struct __ns1__getAllJobnames
{
	struct _ns1__getAllJobnames *ns1__getAllJobnames;	/* optional element of type ns1:getAllJobnames */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllJobProperties
#define SOAP_TYPE___ns1__getAllJobProperties (295)
/* Operation wrapper: */
struct __ns1__getAllJobProperties
{
	struct _ns1__getAllJobProperties *ns1__getAllJobProperties;	/* optional element of type ns1:getAllJobProperties */
};
#endif

#ifndef SOAP_TYPE___ns1__download
#define SOAP_TYPE___ns1__download (299)
/* Operation wrapper: */
struct __ns1__download
{
	struct _ns1__download *ns1__download;	/* optional element of type ns1:download */
};
#endif

#ifndef SOAP_TYPE___ns1__isFolder
#define SOAP_TYPE___ns1__isFolder (303)
/* Operation wrapper: */
struct __ns1__isFolder
{
	struct _ns1__isFolder *ns1__isFolder;	/* optional element of type ns1:isFolder */
};
#endif

#ifndef SOAP_TYPE___ns1__kill
#define SOAP_TYPE___ns1__kill (307)
/* Operation wrapper: */
struct __ns1__kill
{
	struct _ns1__kill *ns1__kill;	/* optional element of type ns1:kill */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllAvailableApplications
#define SOAP_TYPE___ns1__getAllAvailableApplications (311)
/* Operation wrapper: */
struct __ns1__getAllAvailableApplications
{
	struct _ns1__getAllAvailableApplications *ns1__getAllAvailableApplications;	/* optional element of type ns1:getAllAvailableApplications */
};
#endif

#ifndef SOAP_TYPE___ns1__addJobProperties
#define SOAP_TYPE___ns1__addJobProperties (315)
/* Operation wrapper: */
struct __ns1__addJobProperties
{
	struct _ns1__addJobProperties *ns1__addJobProperties;	/* optional element of type ns1:addJobProperties */
};
#endif

#ifndef SOAP_TYPE___ns1__addJobProperty
#define SOAP_TYPE___ns1__addJobProperty (319)
/* Operation wrapper: */
struct __ns1__addJobProperty
{
	struct _ns1__addJobProperty *ns1__addJobProperty;	/* optional element of type ns1:addJobProperty */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllSubmissionLocations
#define SOAP_TYPE___ns1__getAllSubmissionLocations (323)
/* Operation wrapper: */
struct __ns1__getAllSubmissionLocations
{
	struct _ns1__getAllSubmissionLocations *ns1__getAllSubmissionLocations;	/* optional element of type ns1:getAllSubmissionLocations */
};
#endif

#ifndef SOAP_TYPE___ns1__getInterfaceVersion
#define SOAP_TYPE___ns1__getInterfaceVersion (327)
/* Operation wrapper: */
struct __ns1__getInterfaceVersion
{
	struct _ns1__getInterfaceVersion *ns1__getInterfaceVersion;	/* optional element of type ns1:getInterfaceVersion */
};
#endif

#ifndef SOAP_TYPE___ns1__createJob
#define SOAP_TYPE___ns1__createJob (331)
/* Operation wrapper: */
struct __ns1__createJob
{
	struct _ns1__createJob *ns1__createJob;	/* optional element of type ns1:createJob */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllSubmissionLocations1
#define SOAP_TYPE___ns1__getAllSubmissionLocations1 (335)
/* Operation wrapper: */
struct __ns1__getAllSubmissionLocations1
{
	struct _ns1__getAllSubmissionLocations1 *ns1__getAllSubmissionLocations1;	/* optional element of type ns1:getAllSubmissionLocations1 */
};
#endif

#ifndef SOAP_TYPE___ns1__getVersionsOfApplicationOnSite
#define SOAP_TYPE___ns1__getVersionsOfApplicationOnSite (339)
/* Operation wrapper: */
struct __ns1__getVersionsOfApplicationOnSite
{
	struct _ns1__getVersionsOfApplicationOnSite *ns1__getVersionsOfApplicationOnSite;	/* optional element of type ns1:getVersionsOfApplicationOnSite */
};
#endif

#ifndef SOAP_TYPE___ns1__uploadByteArray1
#define SOAP_TYPE___ns1__uploadByteArray1 (343)
/* Operation wrapper: */
struct __ns1__uploadByteArray1
{
	struct _ns1__uploadByteArray1 *ns1__uploadByteArray1;	/* optional element of type ns1:uploadByteArray1 */
};
#endif

#ifndef SOAP_TYPE___ns1__ps_USCOREstring
#define SOAP_TYPE___ns1__ps_USCOREstring (347)
/* Operation wrapper: */
struct __ns1__ps_USCOREstring
{
	struct _ns1__ps_USCOREstring *ns1__ps_USCOREstring;	/* optional element of type ns1:ps_string */
};
#endif

#ifndef SOAP_TYPE___ns1__getSite
#define SOAP_TYPE___ns1__getSite (351)
/* Operation wrapper: */
struct __ns1__getSite
{
	struct _ns1__getSite *ns1__getSite;	/* optional element of type ns1:getSite */
};
#endif

#ifndef SOAP_TYPE___ns1__lastModified
#define SOAP_TYPE___ns1__lastModified (355)
/* Operation wrapper: */
struct __ns1__lastModified
{
	struct _ns1__lastModified *ns1__lastModified;	/* optional element of type ns1:lastModified */
};
#endif

#ifndef SOAP_TYPE___ns1__ls
#define SOAP_TYPE___ns1__ls (359)
/* Operation wrapper: */
struct __ns1__ls
{
	struct _ns1__ls *ns1__ls;	/* optional element of type ns1:ls */
};
#endif

#ifndef SOAP_TYPE___ns1__getApplicationDetails1
#define SOAP_TYPE___ns1__getApplicationDetails1 (363)
/* Operation wrapper: */
struct __ns1__getApplicationDetails1
{
	struct _ns1__getApplicationDetails1 *ns1__getApplicationDetails1;	/* optional element of type ns1:getApplicationDetails1 */
};
#endif

#ifndef SOAP_TYPE___ns1__calculateRelativeJobDirectory
#define SOAP_TYPE___ns1__calculateRelativeJobDirectory (367)
/* Operation wrapper: */
struct __ns1__calculateRelativeJobDirectory
{
	struct _ns1__calculateRelativeJobDirectory *ns1__calculateRelativeJobDirectory;	/* optional element of type ns1:calculateRelativeJobDirectory */
};
#endif

#ifndef SOAP_TYPE___ns1__setJobDescription_USCOREstring
#define SOAP_TYPE___ns1__setJobDescription_USCOREstring (371)
/* Operation wrapper: */
struct __ns1__setJobDescription_USCOREstring
{
	struct _ns1__setJobDescription_USCOREstring *ns1__setJobDescription_USCOREstring;	/* optional element of type ns1:setJobDescription_string */
};
#endif

#ifndef SOAP_TYPE___ns1__logout
#define SOAP_TYPE___ns1__logout (375)
/* Operation wrapper: */
struct __ns1__logout
{
	struct _ns1__logout *ns1__logout;	/* optional element of type ns1:logout */
};
#endif

#ifndef SOAP_TYPE___ns1__submitJob
#define SOAP_TYPE___ns1__submitJob (379)
/* Operation wrapper: */
struct __ns1__submitJob
{
	struct _ns1__submitJob *ns1__submitJob;	/* optional element of type ns1:submitJob */
};
#endif

#ifndef SOAP_TYPE___ns1__uploadByteArray
#define SOAP_TYPE___ns1__uploadByteArray (383)
/* Operation wrapper: */
struct __ns1__uploadByteArray
{
	struct _ns1__uploadByteArray *ns1__uploadByteArray;	/* optional element of type ns1:uploadByteArray */
};
#endif

#ifndef SOAP_TYPE___ns1__cp
#define SOAP_TYPE___ns1__cp (387)
/* Operation wrapper: */
struct __ns1__cp
{
	struct _ns1__cp *ns1__cp;	/* optional element of type ns1:cp */
};
#endif

#ifndef SOAP_TYPE___ns1__getFileSize
#define SOAP_TYPE___ns1__getFileSize (391)
/* Operation wrapper: */
struct __ns1__getFileSize
{
	struct _ns1__getFileSize *ns1__getFileSize;	/* optional element of type ns1:getFileSize */
};
#endif

#ifndef SOAP_TYPE___ns1__deleteFile
#define SOAP_TYPE___ns1__deleteFile (395)
/* Operation wrapper: */
struct __ns1__deleteFile
{
	struct _ns1__deleteFile *ns1__deleteFile;	/* optional element of type ns1:deleteFile */
};
#endif

#ifndef SOAP_TYPE___ns1__upload
#define SOAP_TYPE___ns1__upload (399)
/* Operation wrapper: */
struct __ns1__upload
{
	struct _ns1__upload *ns1__upload;	/* optional element of type ns1:upload */
};
#endif

#ifndef SOAP_TYPE___ns1__getJobDirectory
#define SOAP_TYPE___ns1__getJobDirectory (403)
/* Operation wrapper: */
struct __ns1__getJobDirectory
{
	struct _ns1__getJobDirectory *ns1__getJobDirectory;	/* optional element of type ns1:getJobDirectory */
};
#endif

#ifndef SOAP_TYPE___ns1__setJobDescription
#define SOAP_TYPE___ns1__setJobDescription (407)
/* Operation wrapper: */
struct __ns1__setJobDescription
{
	struct _ns1__setJobDescription *ns1__setJobDescription;	/* optional element of type ns1:setJobDescription */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllSites
#define SOAP_TYPE___ns1__getAllSites (411)
/* Operation wrapper: */
struct __ns1__getAllSites
{
	struct _ns1__getAllSites *ns1__getAllSites;	/* optional element of type ns1:getAllSites */
};
#endif

#ifndef SOAP_TYPE___ns1__getJobDetails_USCOREstring
#define SOAP_TYPE___ns1__getJobDetails_USCOREstring (415)
/* Operation wrapper: */
struct __ns1__getJobDetails_USCOREstring
{
	struct _ns1__getJobDetails_USCOREstring *ns1__getJobDetails_USCOREstring;	/* optional element of type ns1:getJobDetails_string */
};
#endif

#ifndef SOAP_TYPE___ns1__getJobStatus
#define SOAP_TYPE___ns1__getJobStatus (419)
/* Operation wrapper: */
struct __ns1__getJobStatus
{
	struct _ns1__getJobStatus *ns1__getJobStatus;	/* optional element of type ns1:getJobStatus */
};
#endif

#ifndef SOAP_TYPE___ns1__umount
#define SOAP_TYPE___ns1__umount (423)
/* Operation wrapper: */
struct __ns1__umount
{
	struct _ns1__umount *ns1__umount;	/* optional element of type ns1:umount */
};
#endif

#ifndef SOAP_TYPE___ns1__getJobDetails
#define SOAP_TYPE___ns1__getJobDetails (427)
/* Operation wrapper: */
struct __ns1__getJobDetails
{
	struct _ns1__getJobDetails *ns1__getJobDetails;	/* optional element of type ns1:getJobDetails */
};
#endif

#ifndef SOAP_TYPE___ns1__mount1
#define SOAP_TYPE___ns1__mount1 (431)
/* Operation wrapper: */
struct __ns1__mount1
{
	struct _ns1__mount1 *ns1__mount1;	/* optional element of type ns1:mount1 */
};
#endif

#ifndef SOAP_TYPE___ns1__getJobProperty
#define SOAP_TYPE___ns1__getJobProperty (435)
/* Operation wrapper: */
struct __ns1__getJobProperty
{
	struct _ns1__getJobProperty *ns1__getJobProperty;	/* optional element of type ns1:getJobProperty */
};
#endif

#ifndef SOAP_TYPE___ns1__submitSupportRequest
#define SOAP_TYPE___ns1__submitSupportRequest (439)
/* Operation wrapper: */
struct __ns1__submitSupportRequest
{
	struct _ns1__submitSupportRequest *ns1__submitSupportRequest;	/* optional element of type ns1:submitSupportRequest */
};
#endif

#ifndef SOAP_TYPE___ns1__getAllHosts
#define SOAP_TYPE___ns1__getAllHosts (443)
/* Operation wrapper: */
struct __ns1__getAllHosts
{
	struct _ns1__getAllHosts *ns1__getAllHosts;	/* optional element of type ns1:getAllHosts */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (444)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
/* GDIS insert */
char *username;
char *password;
char *myproxyserver;
char *myproxyport;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (445)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (447)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (448)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/

typedef struct _xop__Include _xop__Include;

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getChildrenFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getChildrenFiles *ns1__getChildrenFiles, struct _ns1__getChildrenFilesResponse *ns1__getChildrenFilesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getJobFqan(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getJobFqan *ns1__getJobFqan, struct _ns1__getJobFqanResponse *ns1__getJobFqanResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__mount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__mount *ns1__mount, struct _ns1__mountResponse *ns1__mountResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__login(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__login *ns1__login, struct _ns1__loginResponse *ns1__loginResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getTemplate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getTemplate *ns1__getTemplate, struct _ns1__getTemplateResponse *ns1__getTemplateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getFqans(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getFqans *ns1__getFqans, struct _ns1__getFqansResponse *ns1__getFqansResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__df(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__df *ns1__df, struct _ns1__dfResponse *ns1__dfResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__downloadByteArray(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__downloadByteArray *ns1__downloadByteArray, struct _ns1__downloadByteArrayResponse *ns1__downloadByteArrayResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSubmissionLocationsForApplication2(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSubmissionLocationsForApplication2 *ns1__getSubmissionLocationsForApplication2, struct _ns1__getSubmissionLocationsForApplication2Response *ns1__getSubmissionLocationsForApplication2Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ps(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ps *ns1__ps, struct _ns1__psResponse *ns1__psResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getStagingFileSystemForSubmissionLocation(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getStagingFileSystemForSubmissionLocation *ns1__getStagingFileSystemForSubmissionLocation, struct _ns1__getStagingFileSystemForSubmissionLocationResponse *ns1__getStagingFileSystemForSubmissionLocationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getUserProperty(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getUserProperty *ns1__getUserProperty, struct _ns1__getUserPropertyResponse *ns1__getUserPropertyResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__mkdir(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__mkdir *ns1__mkdir, struct _ns1__mkdirResponse *ns1__mkdirResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getDataLocationsForVO(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDataLocationsForVO *ns1__getDataLocationsForVO, struct _ns1__getDataLocationsForVOResponse *ns1__getDataLocationsForVOResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSubmissionLocationsPerVersionOfApplication(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSubmissionLocationsPerVersionOfApplication *ns1__getSubmissionLocationsPerVersionOfApplication, struct _ns1__getSubmissionLocationsPerVersionOfApplicationResponse *ns1__getSubmissionLocationsPerVersionOfApplicationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getTemplate1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getTemplate1 *ns1__getTemplate1, struct _ns1__getTemplate1Response *ns1__getTemplate1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__downloadByteArray1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__downloadByteArray1 *ns1__downloadByteArray1, struct _ns1__downloadByteArray1Response *ns1__downloadByteArray1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__listHostedApplicationTemplates(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__listHostedApplicationTemplates *ns1__listHostedApplicationTemplates, struct _ns1__listHostedApplicationTemplatesResponse *ns1__listHostedApplicationTemplatesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__deleteFiles *ns1__deleteFiles, struct _ns1__deleteFilesResponse *ns1__deleteFilesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getMessagesSince(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMessagesSince *ns1__getMessagesSince, struct _ns1__getMessagesSinceResponse *ns1__getMessagesSinceResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__calculateAbsoluteJobDirectory(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__calculateAbsoluteJobDirectory *ns1__calculateAbsoluteJobDirectory, struct _ns1__calculateAbsoluteJobDirectoryResponse *ns1__calculateAbsoluteJobDirectoryResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ls_USCOREstring(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ls_USCOREstring *ns1__ls_USCOREstring, struct _ns1__ls_USCOREstringResponse *ns1__ls_USCOREstringResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSubmissionLocationsForApplication1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSubmissionLocationsForApplication1 *ns1__getSubmissionLocationsForApplication1, struct _ns1__getSubmissionLocationsForApplication1Response *ns1__getSubmissionLocationsForApplication1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getApplicationDetails(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getApplicationDetails *ns1__getApplicationDetails, struct _ns1__getApplicationDetailsResponse *ns1__getApplicationDetailsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createJob1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__createJob1 *ns1__createJob1, struct _ns1__createJob1Response *ns1__createJob1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSubmissionLocationsForApplication(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSubmissionLocationsForApplication *ns1__getSubmissionLocationsForApplication, struct _ns1__getSubmissionLocationsForApplicationResponse *ns1__getSubmissionLocationsForApplicationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getDN(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDN *ns1__getDN, struct _ns1__getDNResponse *ns1__getDNResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllJobnames(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllJobnames *ns1__getAllJobnames, struct _ns1__getAllJobnamesResponse *ns1__getAllJobnamesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllJobProperties(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllJobProperties *ns1__getAllJobProperties, struct _ns1__getAllJobPropertiesResponse *ns1__getAllJobPropertiesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__download(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__download *ns1__download, struct _ns1__downloadResponse *ns1__downloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__isFolder(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__isFolder *ns1__isFolder, struct _ns1__isFolderResponse *ns1__isFolderResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__kill(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__kill *ns1__kill, struct _ns1__killResponse *ns1__killResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllAvailableApplications(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllAvailableApplications *ns1__getAllAvailableApplications, struct _ns1__getAllAvailableApplicationsResponse *ns1__getAllAvailableApplicationsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__addJobProperties(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__addJobProperties *ns1__addJobProperties, struct _ns1__addJobPropertiesResponse *ns1__addJobPropertiesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__addJobProperty(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__addJobProperty *ns1__addJobProperty, struct _ns1__addJobPropertyResponse *ns1__addJobPropertyResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllSubmissionLocations(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllSubmissionLocations *ns1__getAllSubmissionLocations, struct _ns1__getAllSubmissionLocationsResponse *ns1__getAllSubmissionLocationsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getInterfaceVersion(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getInterfaceVersion *ns1__getInterfaceVersion, struct _ns1__getInterfaceVersionResponse *ns1__getInterfaceVersionResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createJob(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__createJob *ns1__createJob, struct _ns1__createJobResponse *ns1__createJobResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllSubmissionLocations1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllSubmissionLocations1 *ns1__getAllSubmissionLocations1, struct _ns1__getAllSubmissionLocations1Response *ns1__getAllSubmissionLocations1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getVersionsOfApplicationOnSite(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getVersionsOfApplicationOnSite *ns1__getVersionsOfApplicationOnSite, struct _ns1__getVersionsOfApplicationOnSiteResponse *ns1__getVersionsOfApplicationOnSiteResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__uploadByteArray1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__uploadByteArray1 *ns1__uploadByteArray1, struct _ns1__uploadByteArray1Response *ns1__uploadByteArray1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ps_USCOREstring(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ps_USCOREstring *ns1__ps_USCOREstring, struct _ns1__ps_USCOREstringResponse *ns1__ps_USCOREstringResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSite(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSite *ns1__getSite, struct _ns1__getSiteResponse *ns1__getSiteResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__lastModified(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__lastModified *ns1__lastModified, struct _ns1__lastModifiedResponse *ns1__lastModifiedResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ls(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ls *ns1__ls, struct _ns1__lsResponse *ns1__lsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getApplicationDetails1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getApplicationDetails1 *ns1__getApplicationDetails1, struct _ns1__getApplicationDetails1Response *ns1__getApplicationDetails1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__calculateRelativeJobDirectory(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__calculateRelativeJobDirectory *ns1__calculateRelativeJobDirectory, struct _ns1__calculateRelativeJobDirectoryResponse *ns1__calculateRelativeJobDirectoryResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setJobDescription_USCOREstring(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__setJobDescription_USCOREstring *ns1__setJobDescription_USCOREstring, struct _ns1__setJobDescription_USCOREstringResponse *ns1__setJobDescription_USCOREstringResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__logout(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__logout *ns1__logout, struct _ns1__logoutResponse *ns1__logoutResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__submitJob(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__submitJob *ns1__submitJob, struct _ns1__submitJobResponse *ns1__submitJobResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__uploadByteArray(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__uploadByteArray *ns1__uploadByteArray, struct _ns1__uploadByteArrayResponse *ns1__uploadByteArrayResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__cp(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__cp *ns1__cp, struct _ns1__cpResponse *ns1__cpResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getFileSize(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getFileSize *ns1__getFileSize, struct _ns1__getFileSizeResponse *ns1__getFileSizeResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__deleteFile *ns1__deleteFile, struct _ns1__deleteFileResponse *ns1__deleteFileResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__upload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__upload *ns1__upload, struct _ns1__uploadResponse *ns1__uploadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getJobDirectory(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getJobDirectory *ns1__getJobDirectory, struct _ns1__getJobDirectoryResponse *ns1__getJobDirectoryResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setJobDescription(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__setJobDescription *ns1__setJobDescription, struct _ns1__setJobDescriptionResponse *ns1__setJobDescriptionResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllSites(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllSites *ns1__getAllSites, struct _ns1__getAllSitesResponse *ns1__getAllSitesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getJobDetails_USCOREstring(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getJobDetails_USCOREstring *ns1__getJobDetails_USCOREstring, struct _ns1__getJobDetails_USCOREstringResponse *ns1__getJobDetails_USCOREstringResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getJobStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getJobStatus *ns1__getJobStatus, struct _ns1__getJobStatusResponse *ns1__getJobStatusResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__umount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__umount *ns1__umount, struct _ns1__umountResponse *ns1__umountResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getJobDetails(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getJobDetails *ns1__getJobDetails, struct _ns1__getJobDetailsResponse *ns1__getJobDetailsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__mount1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__mount1 *ns1__mount1, struct _ns1__mount1Response *ns1__mount1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getJobProperty(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getJobProperty *ns1__getJobProperty, struct _ns1__getJobPropertyResponse *ns1__getJobPropertyResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__submitSupportRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__submitSupportRequest *ns1__submitSupportRequest, struct _ns1__submitSupportRequestResponse *ns1__submitSupportRequestResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAllHosts(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAllHosts *ns1__getAllHosts, struct _ns1__getAllHostsResponse *ns1__getAllHostsResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
