
struct keyword_pak keywords[] = 
{
{"sing", E_SINGLE},
{"opti", E_OPTIMIZE},
{"md",   MD},
{"bfgs", BFGS_OPT},
{"rfo",  RFO_OPT},
{"conj", CONJ_OPT},
{"conp", CONP},
{"conv", CONV},
{"mole", MOLE},
{"molm", MOLMEC},
{"molq", MOLQ},
{"qeq", QEQ},
{"free", FREE_ENERGY},
{"zsisa", ZSISA},
{"comp", COMPARE},
{"nosym", NOSYM},
{"fix", FIX},
{"phon", PHONON},
{"eigen", EIGEN},
{"unit", UNIT_HESSIAN},
{"kpoin", KPOINTS},
{"title", TITLE},
{"end",  END},
{"name", NAME},
{"pcel", POLYMER_CELL},
{"pvec", POLYMER_VECTOR},
{"scel", SURFACE_CELL},
{"svec", SURFACE_VECTORS},
{"vect", LATTICE_VECTORS},
{"cell", CELL},
{"cart", CART},
{"frac", FRAC},
{"spac", SPACE},
{"orig", ORIGIN},
{"spec", SPECIES},
{"maxc", MAXCYC},
{"tota", TOTAL_ENERGY},
{"dhkl", D_HKL},
{"sbulk", SBULK_ENERGY},
{"dump", DUMP_FILE},
{"obse", GULP_OBSERVABLES},
{"ensem", ENSEMBLE},
{"temp", TEMPERATURE},
{"super", SUPER_CELL},
{"outp", OUTPUT},
{"libr", GULP_LIBRARY},
/*
{"shrink", SHRINK},
*/
{"switch", SWITCH_ON},
{"gnorm", GNORM},
{"cycle", CYCLE},
{"keyword", KEYWORD},
/* element */
{"elem", ELEMENT},
{"symbol", SYMBOL},
{"number", NUMBER},
{"weight", WEIGHT},
{"cova", COVALENT},
{"ionic", IONIC},
{"vdw", VDW},
{"charge", CHARGE},
{"colour", COLOUR},
/* cif */
{"_audit", CIF_AUDIT},
{"_refine", CIF_REFINE},
{"creation_date", CIF_CREATION_DATE},
{"loop_", CIF_LOOP_START},
{"data_", CIF_DATA_START},
{"_database_code_ICSD", CIF_DATABASE_CODE},
{"_chemical_name_systematic", CIF_CHEMICAL_NAME},
{"_chemical_name_mineral", CIF_MINERAL_NAME},
{"_cell_length_a", CIF_CELL_A},
{"_cell_length_b", CIF_CELL_B},
{"_cell_length_c", CIF_CELL_C},
{"_cell_angle_alpha", CIF_CELL_ALPHA},
{"_cell_angle_beta",  CIF_CELL_BETA},
{"_cell_angle_gamma", CIF_CELL_GAMMA},
{"_symmetry_space_group_name_H-M", CIF_SPACE_NAME},
{"_symmetry_Int_Tables_number", CIF_SPACE_NUM},
{"_symmetry_equiv_pos_site_id", CIF_EQUIV_SITE},
{"_symmetry_equiv_pos_as_xyz", CIF_EQUIV_POS},
{"_atom_site", CIF_ATOM_SITE},
{"label", CIF_LABEL},
{"type_symbol", CIF_TYPE_SYMBOL},
{"cartn_x", CIF_CART_X},
{"cartn_y", CIF_CART_Y},
{"cartn_z", CIF_CART_Z},
{"fract_x", CIF_FRAC_X},
{"fract_y", CIF_FRAC_Y},
{"fract_z", CIF_FRAC_Z},
{"occupancy", CIF_SOF},

/* marvin */
{"basis", MARVIN_BASIS},
{"coord", MARVIN_COORD},

/* gdis data files */
{"\%gdis_elem", GDIS_ELEM_START},
{"\%gdis_end", GDIS_END},

{"last", -1}
};

