# --- gdis Makefile sources

SRC =	main.c model.c coords.c connect.c matrix.c module.c task.c \
	type.c measure.c parse.c edit.c elem.c select.c surface.c \
	analysis.c plots.c spatial.c render.c numeric.c project.c \
	molsurf.c hirshfeld.c zone.c contents.c quaternion.c zmatrix.c \
	library.c geometry.c space.c sginfo.c sgclib.c sgio.c error.c \
	scan.c camera.c defect.c colourlib.c crystal_graph.c mdi.c \
	mesch.c mesch_core.c host.c job.c command.c undo.c count.c \
	ff.c ff_gulp.c test.c \
	file.c file_cif.c file_gulp.c file_gmf.c file_marvin.c file_xtl.c \
	file_arc.c file_xyz.c file_fdf.c file_vasp.c file_gms.c file_diff.c file_xml.c \
	file_abinit.c file_pdb.c file_povray.c file_nwchem.c file_castep.c \
	file_gauss.c file_qe.c file_rietica.c file_geomview.c file_cssr.c file_cel.c \
	file_dmol.c file_dlpoly.c file_bgf.c file_cgf.c file_dlp.c \
	file_gromacs.c file_meta.c file_mol2.c

ifeq ($(USE_GUI), YES)
SRC := $(SRC) gui_main.c gui_canvas.c gui_shorts.c \
	gl_main.c gl_primitives.c gl_stereo.c gl_graph.c gl_varray.c \
	gui_gulp.c gui_siesta.c gui_render.c gui_mdi.c gui_animate.c \
	gui_edit.c gui_surface.c gui_analysis.c gui_defect.c \
	gui_molsurf.c gui_diffract.c gui_gms.c gui_library.c gui_setup.c \
	gui_gperiodic.c gui_plots.c gui_space.c gui_measure.c gui_symmetry.c gui_zmatrix.c \
	gui_dialog.c gui_tree.c gui_task.c gui_help.c gui_monty.c gui_job.c \
        dock.c image.c 
endif

ifeq ($(USE_GRISU), YES)
SRC := $(SRC) grisu_client.c soapC.c soapClient.c logging.c 
endif

